create table if not exists public.authorized_staff (
  id bigint generated by default as identity primary key,
  initials text not null,
  initials_sanitized text not null,
  surname text not null,
  class_name text null,
  designation text null,
  created_at timestamptz not null default now(),
  constraint authorized_staff_class_check check (
    class_name is null or class_name in ('12A','12B','12C','12D','11A','11B','11C','11D','10A','10B','10C','10D','10E','9A','9B','9C','8A','8B','8C','8D')
  )
);

create unique index if not exists authorized_staff_identity_idx
  on public.authorized_staff (initials_sanitized, surname, coalesce(class_name,''), coalesce(designation,''));

alter table public.authorized_staff enable row level security;

drop policy if exists authorized_staff_read_all on public.authorized_staff;
create policy authorized_staff_read_all on public.authorized_staff for select using (true);

-- Helpers: initials_sanitized strips dots and spaces for easier matching

insert into public.authorized_staff (initials, initials_sanitized, surname, class_name)
select v.initials, v.initials_sanitized, v.surname, v.class_name
from (
  values
  ('E J','EJ','DAVID','12A'),
  ('A L','AL','PETER','12B'),
  ('F','F','NAIDOO','12C'),
  ('S','S','HARIPERSAD','12D'),
  ('S K','SK','PILLAY','11A'),
  ('V','V','MAHAYE','11B'),
  ('S','S','SULIMAN','11C'),
  ('V','V','RAJMAN','11D'),
  ('A','A','BUGWANDEEN','10A'),
  ('Z','Z','EBRAHIM','10B'),
  ('N J','NJ','ZULU','10C'),
  ('T','T','NAIDOO','10D'),
  ('A','A','JHUNGBATHUR','10E'),
  ('D','D','MARIE','9A'),
  ('S K','SK','MOODLEY','9B'),
  ('R','R','SEEBRAN','9C'),
  ('A','A','CHETTY','9C'),
  ('R','R','LUTCHMAN','8A'),
  ('A','A','RAMBALI','8B'),
  ('A T','AT','NAIDOO','8C'),
  ('N N','NN','GUMEDE','8D')
) as v(initials, initials_sanitized, surname, class_name)
where not exists (
  select 1 from public.authorized_staff a
  where a.initials_sanitized = v.initials_sanitized
    and a.surname = v.surname
    and coalesce(a.class_name, '') = coalesce(v.class_name, '')
    and coalesce(a.designation, '') = ''
);

insert into public.authorized_staff (initials, initials_sanitized, surname, designation)
select v.initials, v.initials_sanitized, v.surname, v.designation
from (
  values
  ('S','S','BALGOBIND','STAFF'),
  ('S','S','MBONA','STAFF'),
  ('T','T','MKHIZE','STAFF'),
  ('R','R','SIGAMONEY','STAFF'),
  ('K','K','GOVINDASAMI','DEPT. HEAD'),
  ('A X','AX','MAGWAZA','DEPT. HEAD'),
  ('A','A','HARIPARSAD','DEPT. HEAD'),
  ('R','R','DEBBA','DEPT. HEAD'),
  ('L','L','GOVENDER','DEPT. PRINCIPAL'),
  ('D','D','RAMNARIAN','PRINCIPAL'),
  ('S','S','MUNISAMY','ADMIN')
) as v(initials, initials_sanitized, surname, designation)
where not exists (
  select 1 from public.authorized_staff a
  where a.initials_sanitized = v.initials_sanitized
    and a.surname = v.surname
    and coalesce(a.class_name, '') = ''
    and coalesce(a.designation, '') = coalesce(v.designation, '')
);
